import React, { useEffect, useState } from 'react';
import { adminApi, type InvitationResult, type WorkspaceAdminDetail } from './adminApi';
const guid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export function WorkspaceDetailPage({ workspaceId }: { workspaceId: string }) { const [detail, setDetail] = useState<WorkspaceAdminDetail | null>(null); const [error, setError] = useState(''); const [invite, setInvite] = useState(false); const [membership, setMembership] = useState(false); const [result, setResult] = useState<InvitationResult | null>(null); const [email, setEmail] = useState(''); const [name, setName] = useState(''); const [tenantObjectId, setTenantObjectId] = useState(''); const [role, setRole] = useState(''); const [isAteaOperator, setIsAteaOperator] = useState(false); const [success, setSuccess] = useState('');
  const refresh = () => adminApi.getWorkspace(workspaceId).then(setDetail).catch((e) => setError(e instanceof Error ? e.message : 'Workspace details are unavailable.'));
  useEffect(() => { void refresh(); }, [workspaceId]);
  if (error && !detail) return <section className="admin-card"><h1>Workspace details</h1><p role="alert">{error}</p></section>; if (!detail) return <p role="status">Loading workspace details…</p>;
  async function createInvitation(event: React.FormEvent) { event.preventDefault(); try { setResult(await adminApi.createInvitation(workspaceId, { email, displayName: name, expiresAt: new Date(Date.now() + 86400000).toISOString() })); setInvite(false); } catch (e) { setError(e instanceof Error ? e.message : 'Invitation could not be created.'); } }
  async function addMembership(event: React.FormEvent) { event.preventDefault(); if (!guid.test(tenantObjectId)) return setError('Enter a valid Entra object ID.'); if (!email.trim()) return setError('Enter a membership email.'); if (!role.trim()) return setError('Enter a platform role.'); try { await adminApi.addMembership(workspaceId, { tenantObjectId, email: email.trim(), platformRole: role.trim(), isAteaOperator }); setMembership(false); setSuccess('Membership added.'); setEmail(''); setTenantObjectId(''); setRole(''); setIsAteaOperator(false); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Membership could not be added.'); } }
  return <section><p className="eyebrow">Workspace administration</p><h1>{detail.displayName}</h1><p>Tenant ID: {detail.tenantId}</p><p>Status: {detail.connectionStatus}</p>{error && <p role="alert">{error}</p>}{success && <p role="status">{success}</p>}<h2>Memberships</h2>{detail.memberships.length ? <ul>{detail.memberships.map((m) => <li key={m.id}>{m.email} — {m.platformRole} — {m.isAteaOperator ? 'Atea operator' : 'Customer operator'}</li>)}</ul> : <p>No memberships are available.</p>}<button type="button" onClick={() => { setError(''); setMembership(true); }}>Add membership</button>{membership && <form className="admin-card" onSubmit={addMembership}><label>Entra object ID<input aria-label="Entra object ID" value={tenantObjectId} onChange={(e) => setTenantObjectId(e.target.value)} /></label><label>Membership email<input aria-label="Membership email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Platform role<input aria-label="Platform role" value={role} onChange={(e) => setRole(e.target.value)} /></label><label><input aria-label="Atea operator" type="checkbox" checked={isAteaOperator} onChange={(e) => setIsAteaOperator(e.target.checked)} /> Atea operator</label><button type="submit">Add membership</button></form>}<h2>Invitation status</h2>{detail.invitations.length ? <ul>{detail.invitations.map((i) => <li key={i.id}>{i.email} — {i.redeemedAt ? 'Redeemed' : 'Invitation pending'} — expires {i.expiresAt}</li>)}</ul> : <p>No invitations have been created.</p>}<button type="button" onClick={() => setInvite(true)}>Create invitation</button>{invite && <form className="admin-card" onSubmit={createInvitation}><label>Invitation email<input aria-label="Invitation email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Invitee display name<input aria-label="Invitee display name" value={name} onChange={(e) => setName(e.target.value)} required /></label><button type="submit">Create invitation</button></form>}{result && <div className="admin-card" role="status"><p>Invitation URL is a credential-like secret. Share it only through an approved channel and do not store it.</p><code>{result.invitationUrl}</code><p>Expires: {result.expiresAt}</p><button type="button" onClick={() => void navigator.clipboard?.writeText(result.invitationUrl)}>Copy invitation URL</button></div>}</section>; }
