export type ConnectionState = 'awaiting_invitation' | 'consent_required' | 'connected' | 'permission_incomplete' | 'temporarily_unavailable' | 'consent_revoked' | 'connection_failed';

export const messages = {
  appTitle: 'Atea Unified Workplace', enableDarkMode: 'Enable dark mode', disableDarkMode: 'Disable dark mode',
  homeLinkLabel: 'Atea Unified Workplace home', skipToContent: 'Skip to main content', shellLoading: 'Loading workspace shell…', shellUnavailable: 'Workspace shell is unavailable. Try again later.',
  primaryNavigationLabel: 'Primary navigation', tenantContextLabel: 'Current workspace and signed-in user', workspaceLabel: 'Workspace', signedInUserLabel: 'Signed-in user', signedInAs: 'Signed in as', unknownUser: 'Unknown user',
  navOverview: 'Overview', navUsers: 'Users', navLicenses: 'Licenses', navAudit: 'Audit activity', navWorkspaceSettings: 'Workspace settings',
  connectionFresh: 'Connection fresh', connectionNeedsCheck: 'Connection needs check', connectionFreshnessDetail: 'Capability snapshot',
  shellPreviewLabel: 'Preview route', usersTitle: 'Users', usersDescription: 'Directory users will appear here in the next MVP task.', usersEyebrow: 'Directory', usersDirectoryIntro: 'Search and review Microsoft 365 users from the connected tenant.', usersCreateAction: 'Create user', usersRefreshAction: 'Refresh', usersLoading: 'Loading users…', usersUnavailable: 'Users are unavailable. Try again later.', usersNoResults: 'No users match the current filters.', usersNoPermissionTitle: 'Users unavailable', usersNoPermissionBody: 'Directory read permission is required for this workspace.', usersFresh: 'Directory data is fresh', usersStale: 'Directory data may be stale', usersDataUnavailable: 'Directory data is unavailable', usersFetchedAt: 'Fetched', usersNeverFetched: 'Not fetched yet',
  usersSearchLabel: 'Search users', usersSearchPlaceholder: 'Name or user principal name', usersAccountStatusLabel: 'Account status', usersTenantRoleLabel: 'Tenant role', usersTenantRolePlaceholder: 'Global Reader', usersLicenseLabel: 'License', usersLicensePlaceholder: 'SKU ID or part number', usersUnsupportedFilterNotice: 'This filter is not available yet.', usersUserTypeLabel: 'User type', usersFilterAny: 'Any', usersActiveFiltersLabel: 'Active user filters', usersSearchChip: 'Search', usersStatusChip: 'Status', usersTenantRoleChip: 'Tenant role', usersLicenseChip: 'License', usersUserTypeChip: 'User type', usersClearFilters: 'Clear filters', usersClearSearchFilter: 'Clear search filter', usersClearStatusFilter: 'Clear status filter', usersClearTenantRoleFilter: 'Clear tenant role filter', usersClearLicenseFilter: 'Clear license filter', usersClearUserTypeFilter: 'Clear user type filter',
  usersTableLabel: 'Users directory results', usersNameColumn: 'Name', usersUpnColumn: 'User principal name', usersMailColumn: 'Mail', usersTypeColumn: 'User type', usersAccountStatusColumn: 'Account status', usersOpenColumn: 'Open', usersActionsColumn: 'Actions', usersStatusEnabled: 'Enabled', usersStatusDisabled: 'Disabled', usersUnavailableValue: 'Unavailable', usersUnnamedUser: 'Unnamed user', usersOpenAction: 'Open', usersDisableAction: 'Disable', usersDisableDeferredAction: 'Open user details to review and disable this user.', usersPaginationLabel: 'Users pagination', usersPreviousPage: 'Previous page', usersNextPage: 'Next page', userDetailTitle: 'User details', userDetailDescription: 'Review profile, licenses, groups, roles and PIM state from the connected tenant.', userDetailLoading: 'Loading user details…', userDetailUnavailable: 'User details are unavailable. Try again later.', userDetailNotFound: 'This user was removed or is no longer visible in the current tenant.', userIdentitySection: 'Identity', userJobSection: 'Job information', userLicensesSection: 'Assigned licenses', userGroupsSection: 'Group memberships', userRolesPimSection: 'Roles and PIM', userSourceReadOnlyTitle: 'Read-only source of authority', userSectionNoData: 'No records for this section.', userSectionUnavailable: 'This section is unavailable.', userGivenName: 'Given name', userSurname: 'Surname', userJobTitle: 'Job title', userDepartment: 'Department', userOfficeLocation: 'Office location', userMobilePhone: 'Mobile phone', userUsageLocation: 'Usage location', userActiveRoles: 'Active roles', userPimEligibility: 'PIM eligibility', userRequiredCapability: 'Required capability', userPimTask11ActionTitle: 'Activation is implemented in Task 11', userAccountEnabled: 'Account enabled', userAccountDisabled: 'Account disabled', userPimApprovalRequired: 'Approval required', userPimMfaRequired: 'MFA required', userPimJustificationRequired: 'Justification required', userPimTimeLimit: 'Time limit', userPimRequestActivation: 'Request activation for',
  userMutationTarget: 'Target', userMutationProposedChange: 'Proposed change', userMutationAuditNotice: 'This action will be written to the platform audit stream without secrets.', userMutationDestructivePhraseLabel: 'Type DISABLE to confirm', userMutationReviewedConfirmation: 'I reviewed the target, change and required capability.', userMutationCancel: 'Cancel', userMutationConfirm: 'Confirm action', userMutationSaving: 'Saving…', userCreateDialogTitle: 'Create user', userCreateProposedChange: 'Create a cloud user with a temporary password and require password change at next sign-in.', userEditDialogTitle: 'Edit user', userEditProposedChange: 'Update the approved profile fields for this user.', userGroupDialogTitle: 'Change group membership', userGroupAddProposedChange: 'Add this user to the selected group.', userGroupRemoveProposedChange: 'Remove this user from the selected group.', userLicenseDialogTitle: 'Change license assignment', userLicenseAssignProposedChange: 'Assign the selected license to this user.', userLicenseRemoveProposedChange: 'Remove the selected license from this user.', userTemporaryPasswordNotice: 'Temporary password', userTemporaryPasswordForceChange: 'The user must change this password at next sign-in.', userMutationConflict: 'This idempotency key was already used with different details. Review the action before trying again.', userMutationThrottled: 'Microsoft Graph throttled this action. Wait and retry after the suggested interval.',
  licensesTitle: 'Licenses', licensesDescription: 'License assignment workflows will appear here when Microsoft Graph license data is connected.', auditTitle: 'Audit activity', auditDescription: 'Workspace audit events will appear here when audit read endpoints are connected.',
  workspaceSettingsTitle: 'Workspace settings', workspaceSettingsDescription: 'Workspace connection, consent and onboarding settings will appear here for workspace administrators.', notFoundTitle: 'Page not found', notFoundDescription: 'Choose a section from the primary navigation.',
  permissionRequiredTitle: 'Permission required', permissionRequiredBody: 'This workspace section is not available for your current role or tenant state.',
  authSignInTitle: 'Sign in to Atea Unified Workplace', authSignIn: 'Sign in', authPreparing: 'Preparing sign-in…', authSignInError: 'Sign-in could not be started.', authSignInRequired: 'Sign-in is required',
  connectionTitle: 'Microsoft 365 connection', connectionCheck: 'Check connection', connectionConsent: 'Start consent', connectionContinueConsent: 'Continue consent', connectionCopyInvitation: 'Copy invitation instruction', connectionLoading: 'Loading connection status…', connectionUnavailable: 'Connection status is unavailable.', connectionActionFailed: 'That connection action could not be completed. Try again.',
  connectionStaleLabel: 'Connection check is stale', connectionStaleAction: 'Run a new connection check before using connected operations.',
  connectionState: {
    awaiting_invitation: { label: 'Invitation pending', action: 'Invite the customer administrator.' },
    consent_required: { label: 'Consent required', action: 'Ask the customer administrator to grant delegated consent.' },
    connected: { label: 'Connected', action: 'Connection is ready for supported operations.' },
    permission_incomplete: { label: 'Permissions incomplete', action: 'Grant the missing delegated permissions or tenant role.' },
    temporarily_unavailable: { label: 'Temporarily unavailable', action: 'Retry the connection check later.' },
    consent_revoked: { label: 'Consent revoked', action: 'Grant delegated consent again.' },
    connection_failed: { label: 'Connection failed', action: 'Review the handoff instructions and retry consent or connection verification.' },
  } satisfies Record<ConnectionState, { label: string; action: string }>,
} as const;
